name: 'DeepSource Test Coverage Action'
description: 'GitHub Action that uploads test coverage reports to DeepSource for the Test Coverage analyzer.'
author: 'Sanket Saurav <sanket@deepsource.io>'
inputs:
  key:
    description: 'Programming language shortcode for which coverage is reported. Allowed values are — python, go'
    required: true
  coverageFile:
    description: 'Path to the coverage data file. e.g. ./coverage.xml'
    required: true
  dsn:
    description: 'DeepSource DSN of this repository. It is available under Settings → Reporting tab of the repository page on DeepSource.'
    required: true
  failCiOnError:
    description: 'Should the CI build fail if there/'s an error while uploading the report to DeepSource? Allowed values are — true, false'
    default: false
branding:
  color: 'green'
  icon: 'umbrella'
runs:
  using: 'docker'
  image: 'Dockerfile'
